### ISSUE TITLE
store needs If Christmas sang to me cover and link

### ISSUE THREAD

**Issue by kidpan** [tacman/kidpanalley#4]
link https://store.cdbaby.com/cd/kidpanalley9
pic https://www.dropbox.com/s/falaujd7ldvziyv/If%20Christmas%20Sang%20To%20Me%20-%20Final%20Album%20Cover.tiff?dl=0

**Comment by tacman** [comment]
I need the link to add it.

**Comment by tacman** [comment]
@kidpan do you get an email when I tag you like this?

**Comment by tacman** [comment]
https://www.kidpanalley.org/store/

**Comment by tacman** [comment]
Fixed by updating on cdbaby
